version: "3"
services:
  mysql:
    environment:
      MYSQL_USER: nktn
      MYSQL_PASSWORD: mysql@devNktn
      MYSQL_DATABASE: kakeibo
      TZ: Asia/Tokyo
    ports:
      - 13306:3306
    build:
      context: .
      dockerfile: Dockerfile
    image: mysql-container:0.1
    volumes:
      # 起動時に自動で実行されるスクリプトおよびSQLファイルをマウント
      - ./init:/docker-entrypoint-initdb.d